const actionTypes = {
  CHANGE_VIEW_TYPE: "CHANGE_VIEW_TYPE",
  SORT_TYPE: "SORT_TYPE",
  SORT_SUBTYPE: "SORT_SUBTYPE",
  FAVOURITE: "FAVOURITE",
  LANG: "LANG",
  SET_USERS: "SET_USERS",
  CHANGE_VALUE: "CHANGE_VALUE"
};

export default actionTypes;
